# Generated by Django 3.1.3 on 2021-01-16 10:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0002_sodesh'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDhakaCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('landuse', models.CharField(blank=True, max_length=50, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_field', models.CharField(blank=True, db_column='father__', max_length=50, null=True)),
                ('spouse_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('national_i', models.IntegerField(blank=True, null=True)),
                ('tin_field', models.IntegerField(blank=True, db_column='tin__', null=True)),
                ('land_price', models.IntegerField(blank=True, null=True)),
                ('mou_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mou_jl', models.CharField(blank=True, max_length=50, null=True)),
                ('pur_date', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=50, null=True)),
                ('inst_date', models.CharField(blank=True, max_length=50, null=True)),
                ('land_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('area_bigha', models.CharField(blank=True, max_length=50, null=True)),
                ('area_acre', models.CharField(blank=True, max_length=50, null=True)),
                ('area_katha', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'new_dhaka_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiverParkModelTown',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('area_katha', models.FloatField(blank=True, null=True)),
                ('area_acre', models.FloatField(blank=True, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_field', models.CharField(blank=True, db_column='father__', max_length=50, null=True)),
                ('spouse_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('national_i', models.CharField(blank=True, max_length=50, null=True)),
                ('tin_field', models.CharField(blank=True, db_column='tin__', max_length=50, null=True)),
                ('land_price', models.CharField(blank=True, max_length=50, null=True)),
                ('mou_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mou_jl', models.CharField(blank=True, max_length=50, null=True)),
                ('pur_date', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=50, null=True)),
                ('inst_date', models.CharField(blank=True, max_length=50, null=True)),
                ('land_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('area_bigha', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('geom2d', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
            ],
            options={
                'db_table': 'river_park_model_town',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Swadesh',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('area_sqft', models.FloatField(blank=True, null=True)),
                ('area_bigha', models.FloatField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, max_length=20, null=True)),
                ('plot_no', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_field', models.CharField(blank=True, db_column='father__', max_length=50, null=True)),
                ('spouse_nam', models.CharField(blank=True, max_length=50, null=True)),
                ('national_i', models.BigIntegerField(blank=True, null=True)),
                ('tin_field', models.BigIntegerField(blank=True, db_column='tin___', null=True)),
                ('land_price', models.BigIntegerField(blank=True, null=True)),
                ('mou_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mou_jl', models.CharField(blank=True, max_length=50, null=True)),
                ('pur_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('inst_date', models.DateField(blank=True, null=True)),
                ('land_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('area_katha', models.CharField(blank=True, max_length=50, null=True)),
                ('area_acre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'swadesh',
                'managed': False,
            },
        ),
    ]
